name: Test Emulator Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt install build-essential libsdl2-dev libsdl2-ttf-dev libfftw3-dev swig python3 zip fonts-freefont-ttf
    - name: make emu
      run: make emu

  darwin-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: brew install sdl2 sdl2_ttf fftw swig
    - name: make emu
      run: make emu

